import { describe, expect, it } from "vitest";
import { generateReferralCode, isValidReferralCode } from "../src/referrals.js";

describe("generateReferralCode", () => {
  it("returns the requested length", () => {
    expect(generateReferralCode(6)).toHaveLength(6);
    expect(generateReferralCode(10)).toHaveLength(10);
  });

  it("uses only Crockford-safe characters (no 0/O/1/l/I/U)", () => {
    const banned = ["0", "O", "1", "l", "I", "U"];
    for (let i = 0; i < 100; i++) {
      const code = generateReferralCode(10);
      for (const ch of banned) expect(code).not.toContain(ch);
    }
  });

  it("rejects nonsense lengths", () => {
    expect(() => generateReferralCode(3)).toThrow();
    expect(() => generateReferralCode(33)).toThrow();
  });

  it("produces distinct codes across many calls", () => {
    const seen = new Set<string>();
    for (let i = 0; i < 1000; i++) seen.add(generateReferralCode(8));
    expect(seen.size).toBeGreaterThan(990);
  });
});

describe("isValidReferralCode", () => {
  it("accepts a code generated by generateReferralCode", () => {
    expect(isValidReferralCode(generateReferralCode(6), 6)).toBe(true);
  });

  it("rejects wrong length", () => {
    expect(isValidReferralCode("ABCDE", 6)).toBe(false);
    expect(isValidReferralCode("ABCDEFG", 6)).toBe(false);
  });

  it("rejects non-string types", () => {
    expect(isValidReferralCode(null, 6)).toBe(false);
    expect(isValidReferralCode(123456, 6)).toBe(false);
    expect(isValidReferralCode(undefined, 6)).toBe(false);
  });

  it("rejects banned characters", () => {
    expect(isValidReferralCode("0BCDEF", 6)).toBe(false);
    expect(isValidReferralCode("ABCDE1", 6)).toBe(false);
  });
});
